language: php

php:
  - '7.1'
  - '7.2.0alpha3'

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v
